### ISSUE TITLE
Repository License file

### ISSUE THREAD

**Issue by RNabel** [gimite/android-native-exe-demo#1]
Hi there,
Thank you for putting this repo and the associated blog post up. Could you add a license file to the repository so it can be used by others? I'm happy to raise a PR to add a license if required :)

Many thanks in advance!

**Comment by gimite** [comment]
Just added a LICENSE file. But the sample code is very old (last updated for Android 2.3). I haven't verified but there is a good chance that it doesn't work as is in recent versions of Android. Use of NDK would be probably a better choice of running native code as part of your app.

**Comment by RNabel** [comment]
Awesome, thank you! I can confirm that this works with modern (API level 26+) versions of Android. I'll use this as inspiration for an Android-native gtest test runner.
